apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pff
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend
          image: ghcr.io/ORG/REPO:backend-latest   # CI will patch tag
          env:
            - name: DB_CONNECTION   # same keys you had in .env
              value: mysql
            - name: DB_HOST
              value: mysql
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: pff
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
          ports:
            - containerPort: 9000   # php-fpm listens here
          resources:
            requests: { cpu: "100m", memory: "256Mi" }
            limits:   { cpu: "250m", memory: "512Mi" }
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pff
spec:
  type: ClusterIP
  selector: { app: backend }
  ports:
    - port: 9000
      targetPort: 9000
