apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: pff
spec:
  replicas: 2
  selector:
    matchLabels: { app: backend }
  template:
    metadata:
      labels: { app: backend }
    spec:
      containers:
        - name: backend                 # match set-image
          image: ghcr.io/fattoumifahd/pff:backend-latest
          ports:
            - containerPort: 9000       # php-fpm listens here
          env:
            - name: DB_CONNECTION
              value: mysql
            - name: DB_HOST
              value: mysql              # service name above
            - name: DB_PORT
              value: "3306"
            - name: DB_DATABASE
              value: pff
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: ""                 # empty because we allowed empty pwd
      # Add this block only if your GHCR repo is private:
      # imagePullSecrets:
      #   - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: pff
spec:
  selector: { app: backend }
  ports:
    - port: 9000
      targetPort: 9000
