name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]
    paths:
      - "k8s/**"
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: self-hosted          # ← your Windows runner

    steps:
      # 1) Checkout repo
      - uses: actions/checkout@v4

      # 2) Ensure kubectl v1.30 is on PATH
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0

      # 3) Apply (or update) all manifests
      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      # 4) Patch the images with current commit SHA
      - name: Patch image tags
        shell: powershell
        run: |
          # short 8-char SHA
          $shortSha = $Env:GITHUB_SHA.Substring(0,8)

          # repo name is always lower-case
          $repo = "${Env:GITHUB_REPOSITORY}".ToLower()   # e.g. fattoumifahd/pff

          $backendImg  = "ghcr.io/$repo:backend-$shortSha"
          $frontendImg = "ghcr.io/$repo:frontend-$shortSha"

          Write-Host "Updating backend image to $backendImg"
          kubectl -n pff set image deployment/backend  backend=$backendImg  --record

          Write-Host "Updating frontend image to $frontendImg"
          kubectl -n pff set image deployment/frontend web=$frontendImg     --record

      # 5) Wait (max 3 min) for both rollouts
      - name: Wait for rollouts
        run: |
          kubectl rollout status deployment/backend  -n pff --timeout=180s
          kubectl rollout status deployment/frontend -n pff --timeout=180s
