name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]         
    paths:
      - "k8s/**"
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

  
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

  


    - name: Apply raw manifests
      run: |
        kubectl apply -f k8s/

 
    - name: Patch image tags
      shell: powershell           
      run: |
        # Compose the two image tags
        $backendImg  = "ghcr.io/${{ github.repository }}:backend-${{ github.sha }}"
        $frontendImg = "ghcr.io/${{ github.repository }}:frontend-${{ github.sha }}"

        Write-Host "Updating backend to $backendImg"
        kubectl -n pff set image deployment/backend  backend=$backendImg --record

        Write-Host "Updating frontend to $frontendImg"
        kubectl -n pff set image deployment/frontend web=$frontendImg --record

    - name: Wait for rollouts
      run: |
        kubectl rollout status deployment/backend  -n pff
        kubectl rollout status deployment/frontend -n pff 
