name: Deploy to Kubernetes

on:
  push:
    branches: [ master ]          # adapte si ta branche par défaut est 'main'
    paths:
      - "k8s/**"
      - "backend/**"
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # ───────────────────────────────
    # 1) Récupérer le code
    # ───────────────────────────────
    - uses: actions/checkout@v3

    # ───────────────────────────────
    # 2) Installer kubectl
    # ───────────────────────────────
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.30.0

    # ───────────────────────────────
    # 3) Injecter le kubeconfig
    # ───────────────────────────────
    - name: Write kubeconfig
      run: |
        mkdir -p "$HOME/.kube"
        echo "${KUBE_CONFIG}" | base64 -d > "$HOME/.kube/config"
        chmod 600 "$HOME/.kube/config"
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

    # ───────────────────────────────
    # 4) Appliquer les manifests
    # ───────────────────────────────
    - name: Apply raw manifests
      run: |
        kubectl apply -f k8s/

    # ───────────────────────────────
    # 5) Mettre à jour les images
    # ───────────────────────────────
    - name: Patch image tags
      run: |
        # Nom d’image GHCR : ghcr.io/{owner}/{repo}:{backend|frontend}-{sha}
        BACKEND_IMG="ghcr.io/${{ github.repository }}:backend-${{ github.sha }}"
        FRONTEND_IMG="ghcr.io/${{ github.repository }}:frontend-${{ github.sha }}"

        echo "Updating backend to $BACKEND_IMG"
        kubectl -n pff set image deployment/backend  backend=$BACKEND_IMG --record

        echo "Updating frontend to $FRONTEND_IMG"
        kubectl -n pff set image deployment/frontend web=$FRONTEND_IMG --record

    # ───────────────────────────────
    # 6) Attendre le déploiement
    # ───────────────────────────────
    - name: Wait for rollouts
      run: |
        kubectl rollout status deployment/backend  -n pff
        kubectl rollout status deployment/frontend -n pff 
