name: Laravel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        # allow MySQL a bit of startup time
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      # match your config/database.php defaults
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: testing
      DB_USERNAME: root
      DB_PASSWORD: secret

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo_mysql, xml, curl, zip
          ini-values: post_max_size=256M, memory_limit=512M
          coverage: none

      - name: Get Composer cache
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependencies
        working-directory: backend
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Copy .env and generate key
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..15}; do
            mysql -h127.0.0.1 -uroot -psecret -e "SELECT 1" && break
            sleep 2
          done

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always --stop-on-failure
